spring:

  datasource:
    url: jdbc:h2:mem:demoDB
    driverClassName: org.h2.Driver
    username: sa
    Password: 165631

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Hibernate properties
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
  sql:
      init:
        mode: always

  h2:
    console.enabled: true

# Logging properties
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: DEBUG


